#	$OpenBSD: Makefile,v 1.4 2017/07/09 21:23:19 espie Exp $

.PATH:	${.CURDIR}/..

PROG=	lesskey
SRCS=	lesskey.c version.c

BINDIR=	/usr/local/bin
SHAREDIR= /usr/local/share
MANDIR= /usr/local/share/man/man

CFLAGS+=-I${.CURDIR}/..

.include <bsd.prog.mk>
